# APPLICATION
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webk9s
spec:
  selector:
    matchLabels:
      app: webk9s
  replicas: 1 
  template:
    metadata:
      labels:
        app: webk9s
    spec:
      serviceAccountName: sa-k9s
      containers:
      - name: webk9s
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
          protocol: TCP
          name: webk9s
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}